---
service:
  # Address to listen on, default: localhost:6883
  listen: 'localhost:6883'
  # URL path for metrics exposure, default: /metrics
  metrics_path: '/metrics'
  # msgs published on this topic must be in json format with a vector of topics to monitor
  # eg.: "[t1/sub_t1, t1/sub_t2, t3/+]", prometheus-mosquitto-exporter will create counters for those topics
  topic_listener: 'prometheus-mqtt-exporter/listen'
mqtt:
  # MQTT authentication
  auth:
    user: 'mqtt_user'
    password: 'mqtt_password'
  # MQTT broker address, scheme://address
  # Valid schemes are tcp and ssl
  broker: 'tls://mqtt.name.or.addr.ess'
  # CA file to use for server certificate validation, default: /etc/ssl/certs/ca-certificates.crt
  ca_file: '/etc/ssl/certs/ca-certificates.crt'
  
  # Client side certificate and key, that must be defined depending on the mqtt broker configuration
  client_cert_file: ''
  client_key_file: ''
  # Disable verification of servers SSL certificate
  insecure_ssl: false
  # maximal time in seconds for reconnect in seconds
  retry_interval: 60
  # timeout for connection establishment in seconds
  timeout: 5
  
  



